from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
DB_PATH = DATA_DIR / "dt_health.sqlite"

EXPECTED_COLUMNS = [
    "Zone",
    "Circle",
    "Division",
    "Subdivision",
    "substation",
    "Feeder Name",
    "DT Code",
    "DT Meter number",
    "DT Name",
    "HES",
    "MF",
    "KVA Rating",
    "kWh",
    "kVah",
    "Power Factor",
    "Avg KVA",
    "Maximum KVA",
    "Maximum kVA_Date",
    "R-Phase Max Current",
    "Y-Phase Max Current",
    "B-Phase Max Current",
    "Unbalance(RY)",
    "Unbalance(YB)",
    "Unbalance(BR)",
    "DT Loading",
    "Load Factor",
    "Utilization Factor",
    "DT Loading Status",
    "DT Unbalance Status",
    "Total Hours",
    "Power Off Hours",
    "Power On Hours",
]

RENAME_MAP = {
    "Zone": "zone",
    "Circle": "circle",
    "Division": "division",
    "Subdivision": "subdivision",
    "substation": "substation",
    "Feeder Name": "feeder_name",
    "DT Code": "dt_code",
    "DT Meter number": "dt_meter_number",
    "DT Name": "dt_name",
    "HES": "hes",
    "MF": "mf",
    "KVA Rating": "kva_rating",
    "kWh": "kwh",
    "kVah": "kvah",
    "Power Factor": "power_factor",
    "Avg KVA": "avg_kva",
    "Maximum KVA": "maximum_kva",
    "Maximum kVA_Date": "maximum_kva_date",
    "R-Phase Max Current": "r_phase_max_current",
    "Y-Phase Max Current": "y_phase_max_current",
    "B-Phase Max Current": "b_phase_max_current",
    "Unbalance(RY)": "unbalance_ry",
    "Unbalance(YB)": "unbalance_yb",
    "Unbalance(BR)": "unbalance_br",
    "DT Loading": "dt_loading_source",
    "Load Factor": "load_factor",
    "Utilization Factor": "utilization_factor",
    "DT Loading Status": "dt_loading_status_source",
    "DT Unbalance Status": "dt_unbalance_status_source",
    "Total Hours": "total_hours",
    "Power Off Hours": "power_off_hours",
    "Power On Hours": "power_on_hours",
}

NUMERIC_COLUMNS = [
    "mf",
    "kva_rating",
    "kwh",
    "kvah",
    "power_factor",
    "avg_kva",
    "maximum_kva",
    "r_phase_max_current",
    "y_phase_max_current",
    "b_phase_max_current",
    "unbalance_ry",
    "unbalance_yb",
    "unbalance_br",
    "dt_loading_source",
    "load_factor",
    "utilization_factor",
    "total_hours",
    "power_off_hours",
    "power_on_hours",
]

TEXT_COLUMNS = [
    "zone",
    "circle",
    "division",
    "subdivision",
    "substation",
    "feeder_name",
    "dt_code",
    "dt_meter_number",
    "dt_name",
    "hes",
]

STATUS_ORDER = ["normal", "low", "medium", "high"]
STATUS_SCORES = {"normal": 0, "low": 1, "medium": 2, "high": 3}

EXPORT_COLUMNS = [
    "period",
    "zone",
    "circle",
    "division",
    "subdivision",
    "substation",
    "feeder_name",
    "dt_code",
    "dt_meter_number",
    "dt_name",
    "kva_rating",
    "maximum_kva",
    "dt_loading",
    "dt_loading_status",
    "max_unbalance",
    "dt_unbalance_status",
    "power_off_hours",
    "criticality_score",
    "prediction_target_period",
    "predicted_failure_probability",
    "prediction_method",
]
